// AUTO-GENERATED by scripts/generate-account-slot-families.mjs.
// Do not edit by hand — edit server/pkg/agent/account_slot_families.json
// and run `pnpm generate:account-slot-families`.

/**
 * One CLI family that owns a numbered account-slot registry: slot 1 is the
 * CLI's own directory (`baseDir`), slot N is `<accountDirPrefix>N`, and an
 * agent's registered slots live under `runtime_config[runtimeConfigKey]` as
 * `{ accounts: number[] }`.
 *
 * Single source of truth: `server/pkg/agent/account_slot_families.json`. The
 * Go daemon embeds that JSON for its account probe; this file is regenerated
 * from it. A CLI absent from this table (codex, cursor) cannot be rebound by
 * the daemon and therefore has no slots to register.
 */
export type AccountSlotFamily = {
  readonly cli: string;
  readonly baseDir: string;
  readonly accountDirPrefix: string;
  /** `custom_args:<flag>` or `env:<KEY>` — how a bound slot reaches the CLI. */
  readonly lever: string;
  readonly runtimeConfigKey: string;
  /** Seeds the list for an agent that never saved one. Always starts with 1. */
  readonly defaultAccounts: readonly number[];
  /**
   * True only where the daemon detects an exhausted quota and moves to the
   * next slot. Every other family's slots are a manual registry.
   */
  readonly rotatesOnQuota: boolean;
};

export const MAX_ACCOUNT_SLOT_NUMBER = 32;

export const ACCOUNT_SLOT_FAMILIES: readonly AccountSlotFamily[] = [
  {
    cli: "agy",
    baseDir: ".gemini",
    accountDirPrefix: ".gemini-account",
    lever: "custom_args:--gemini_dir",
    runtimeConfigKey: "agy_slots",
    defaultAccounts: [1, 2, 3],
    rotatesOnQuota: true,
  },
  {
    cli: "dsh",
    baseDir: ".dsh",
    accountDirPrefix: ".dsh-account",
    lever: "env:DSH_HOME",
    runtimeConfigKey: "dsh_slots",
    defaultAccounts: [1],
    rotatesOnQuota: false,
  },
  {
    cli: "claude",
    baseDir: ".claude",
    accountDirPrefix: ".claude-account",
    lever: "env:CLAUDE_CONFIG_DIR",
    runtimeConfigKey: "claude_slots",
    defaultAccounts: [1],
    rotatesOnQuota: false,
  },
];

export function accountSlotFamily(cli: string): AccountSlotFamily | null {
  return ACCOUNT_SLOT_FAMILIES.find((family) => family.cli === cli) ?? null;
}
